name: Merge template branch to main branch

on:
  push:
    branches:
      - template

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: mkdir site;
          cd ./site;
          git clone https://github.com/LibraHeresy/site.git -b main;
          git clone https://github.com/LibraHeresy/site.git -b template;
      - name: Merge
        run: git config --global use.email "1141614570@qq.com";
          git config --global use.email "LibraHeresy";
          git checkout main;
          git merge template --strategy=theirs;
          git push;
