name: Merge template branch to main branch

on:
  push:
    branches:
      - template

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: git clone https://github.com/LibraHeresy/site.git -b template
      - name: Config
        run: git config --global use.email "1141614570@qq.com" && git config --global use.email "LibraHeresy"
      - name: CheckOut
        run: cd ./site && git pull origin main && git checkout main
      - name: Merge
        run: cd ./site && git merge template -X diff-algorithm=theirs && git push
